version: "3"

services:
  # Note: If you are assigning a custom name to your tattoo_db service on the line below, make sure it does not contain underscores
  tattoo_db:
    container_name: tattoo_db
    image: "postgres:latest"
    environment:
      POSTGRES_USER: tattoo_user
      POSTGRES_PASSWORD: passssword
      POSTGRES_DB: tattoo
    ports:
      - 5432:5432
    volumes:
      - /volumes/pg-data/tattoo/:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d/
    networks:
      - tattoo_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tattoo_user", "-d", "tattoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.4
    depends_on:
      tattoo_db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      postgresql_connection_uri: "postgresql://tattoo_user:passssword@tattoo_db:5432/tattoo"
    networks:
      - tattoo_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tattoo_network:
    driver: bridge
